///Hive Type
const int HIVE_TYPE_SYS_VO = 1;
const int HIVE_TYPE_WEATHER_VO = 2;
const int HIVE_TYPE_MAIN_VO = 3;
const int HIVE_TYPE_WIND_VO = 4;
const int HIVE_TYPE_COORD_VO = 5;
const int HIVE_TYPE_DAILY_VO = 6;
const int HIVE_TYPE_TEMP_VO = 7;

const int HIVE_TYPE_DAILY_LIST_FOR_HIVE_VO = 8;

///Box Names
const String BOX_NAME_LOCATION_BY_LAT_LON = "BOX_NAME_LOCATION_BY_LAT_LON";
const String BOX_NAME_WEATHER_VO = "BOX_NAME_WEATHER_VO";
const String BOX_NAME_MAIN_VO = "BOX_NAME_MAIN_VO";
const String BOX_NAME_WIND_VO = "BOX_NAME_WIND_VO";
const String BOX_NAME_COORD_VO = "BOX_NAME_COORD_VO";
const String BOX_NAME_DAILY_VO = "BOX_NAME_DAILY_VO";
const String BOX_NAME_TEMP_VO = "BOX_NAME_TEMP_VO";
const String BOX_NAME_DAILY_LIST_FOR_HIVE_VO = "BOX_NAME_DAILY_LIST_FOR_HIVE_VO";